language: generic

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Build images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy

  # Tagging images
  - docker tag udagram-api-feed ninhnvt/udagram-api-feed:v2
  - docker tag udagram-api-user ninhnvt/udagram-api-user:v2
  - docker tag udagram-frontend ninhnvt/udagram-frontend:v4
  - docker tag reverseproxy ninhnvt/reverseproxy:v2

  # Push images to DockerHub
  - docker push ninhnvt/udagram-api-feed:v2
  - docker push ninhnvt/udagram-api-user:v2
  - docker push ninhnvt/udagram-frontend:v4
  - docker push ninhnvt/reverseproxy:v2
  
