version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Node.js Docker image (you can change the version if needed)
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Checks out the code from the repository
      - setup_remote_docker:
          docker_layer_caching: true  # Enables Docker layer caching for faster builds
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker Images
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t reverseproxy ./reverseproxy
      - run:
          name: Tag Docker Images
          command: |
            docker tag udagram-api-feed ninhnvt/udagram-api-feed:v2
            docker tag udagram-api-user ninhnvt/udagram-api-user:v2
            docker tag udagram-frontend ninhnvt/udagram-frontend:v4
            docker tag reverseproxy ninhnvt/reverseproxy:v2
      - run:
          name: Push Docker Images
          command: |
            docker push ninhnvt/udagram-api-feed:v2
            docker push ninhnvt/udagram-api-user:v2
            docker push ninhnvt/udagram-frontend:v4
            docker push ninhnvt/reverseproxy:v2

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - develop
